spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  datasource:
    url: jdbc:${DB_URI}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${OIDC_CLIENT_ID:endpoint-insights}
            client-secret: ${OIDC_CLIENT_SECRET:your-secret-here}
            redirect-uri:  ${OIDC_CLIENT_REDIRECT_URI:hhttp://localhost:8080/oauth2/authorization/oidc}
            authorization-grant-type: authorization_code
            scope: openid,profile,email,groups
            client-name: OIDC
        provider:
          oidc:
            issuer-uri: https://auth.example.com
            authorization-uri: https://auth.example.com/api/oidc/authorization
            token-uri: https://auth.example.com/api/oidc/token
            user-info-uri: https://auth.example.com/api/oidc/userinfo
            jwk-set-uri: https://auth.example.com/jwks.json

  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: ${MAIL_FROM:noreply@example.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jmeter:
  home: ${JMETER_HOME}

app:
  authentication:
    enabled: true
    groups:
      write: "ei:write"
      read: "ei:read"
    claims:
      username: ${AUTH_USERNAME_CLAIM:preferred_username}
      email: ${AUTH_EMAIL_CLAIM:email}
      groups: ${AUTH_GROUPS_CLAIM:groups}
  git:
    checkout-dir: ${GIT_CHECKOUT_DIR:./.git-checkouts}
  cors:
    allow-credentials: true
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed-origins:
      - "https://localhost:8080/oauth2/authorization/oidc"

server:
  port: 8080

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING:INFO}
    org.springframework.boot: ${LOG_LEVEL_SPRING:INFO}
    org.hibernate: ${LOG_LEVEL_JPA:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_SQL:WARN}
    org.springframework.data.jpa: ${LOG_LEVEL_JPA:WARN}
    com.vsp.endpointinsightsapi: ${LOG_LEVEL_APP:INFO}
    com.vsp.endpointinsightsapi.aspects.LogAspect: ${LOG_LEVEL_APP:INFO}
    com.vsp.endpointinsightsapi.service: ${LOG_LEVEL_APP:INFO}
    com.vsp.endpointinsightsapi.controller: ${LOG_LEVEL_APP:INFO}
    com.vsp.endpointinsightsapi.repository: ${LOG_LEVEL_APP:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/application.log}
    max-size: ${LOG_FILE_MAX_SIZE:10MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: 1GB