CREATE TABLE job_schedule (
    schedule_id SERIAL PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES job(job_id) ON DELETE CASCADE,
    cron_expr VARCHAR(50) NOT NULL,
    timezone VARCHAR(50) NOT NULL DEFAULT 'PDT',
    next_run_at TIMESTAMP,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
