CREATE TABLE IF NOT EXISTS job (
    created_date TIMESTAMPTZ,
    updated_date TIMESTAMPTZ NOT NULL,
    job_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    test_type VARCHAR(20) NOT NULL,
    compile_command VARCHAR(255),
    created_by VARCHAR(255),
    description VARCHAR(255),
    git_url VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    run_command VARCHAR(255),
    updated_by VARCHAR(255) NOT NULL,
    config JSONB,
    git_auth_type VARCHAR(20),
    git_password VARCHAR(255),
    git_ssh_passphrase VARCHAR(255),
    git_ssh_private_key TEXT,
    git_username VARCHAR(255),
    jmeter_test_name VARCHAR(255),
    CONSTRAINT job_pkey PRIMARY KEY (job_id),
    CONSTRAINT job_git_auth_type_check CHECK ((git_auth_type::TEXT = ANY ((ARRAY['NONE', 'BASIC', 'SSH_KEY'])::TEXT[]))),
    CONSTRAINT job_status_check CHECK ((status::TEXT = ANY ((ARRAY['PENDING', 'RUNNING', 'COMPLETED', 'FAILED'])::TEXT[]))),
    CONSTRAINT job_test_type_check CHECK ((test_type::TEXT = ANY ((ARRAY['PERF', 'INTEGRATION', 'E2E'])::TEXT[])))
);
