CREATE TABLE IF NOT EXISTS mailing_recipient (
    mailing_recipient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    display_name TEXT,
    source TEXT,
    is_suppressed BOOLEAN NOT NULL DEFAULT FALSE,
    suppressed_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mailing_recipient_email
    ON mailing_recipient (email);
