CREATE TABLE IF NOT EXISTS job_schedule (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    cron_expr VARCHAR(50) NOT NULL,
    is_enabled BOOLEAN NOT NULL,
    next_run_at TIMESTAMP(6),
    timezone VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP(6)
);
