-- ==========================================
-- Mailing List + Mailing Recipient tables
-- ==========================================

BEGIN;

-- enum for state
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_membership_status') THEN
CREATE TYPE mailing_membership_status
    AS ENUM ('ACTIVE', 'UNSUBSCRIBED', 'BOUNCED');
END IF;
END$$;

-- Main Mailing list
CREATE TABLE IF NOT EXISTS mailing_list (
                                            mailing_list_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            name             TEXT NOT NULL,
                                            description      TEXT,
                                            is_active        BOOLEAN NOT NULL DEFAULT TRUE,

                                            created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       TEXT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by       TEXT
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_mailing_list_name
    ON mailing_list (name);

-- Recipients table
CREATE TABLE IF NOT EXISTS mailing_recipient (
                                                 mailing_recipient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                 email                TEXT NOT NULL,   -- keep raw standard type

                                                 first_name           TEXT,
                                                 last_name            TEXT,
                                                 display_name         TEXT,
                                                 source               TEXT,

                                                 is_suppressed        BOOLEAN NOT NULL DEFAULT FALSE,
                                                 suppressed_reason    TEXT,

                                                 created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by           TEXT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           TEXT
    );

-- Normalize emails to lowercase at the database boundary
CREATE OR REPLACE FUNCTION normalize_email_lower()
RETURNS TRIGGER AS $$
BEGIN
    NEW.email = LOWER(NEW.email);
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_normalize_recipient_email
    BEFORE INSERT OR UPDATE ON mailing_recipient
                         FOR EACH ROW
                         EXECUTE FUNCTION normalize_email_lower();

--Uniqueness based on the stored value (already lowercased)
CREATE UNIQUE INDEX IF NOT EXISTS ux_mailing_recipient_email
    ON mailing_recipient (email);

--Join table
CREATE TABLE IF NOT EXISTS mailing_list_recipient (
                                                      mailing_list_id      BIGINT NOT NULL,
                                                      mailing_recipient_id BIGINT NOT NULL,

                                                      status               mailing_membership_status NOT NULL DEFAULT 'ACTIVE',

                                                      added_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    added_by             TEXT,
    removed_at           TIMESTAMPTZ,
    removed_by           TEXT,

    PRIMARY KEY (mailing_list_id, mailing_recipient_id),

    CONSTRAINT fk_mlr_list
    FOREIGN KEY (mailing_list_id)
    REFERENCES mailing_list (mailing_list_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_mlr_recipient
    FOREIGN KEY (mailing_recipient_id)
    REFERENCES mailing_recipient (mailing_recipient_id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS ix_mlr_recipient
    ON mailing_list_recipient (mailing_recipient_id);

CREATE INDEX IF NOT EXISTS ix_mlr_list_status
    ON mailing_list_recipient (mailing_list_id, status);

--Auto-updated timestamp
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mailing_list_updated_at'
    ) THEN
CREATE TRIGGER trg_mailing_list_updated_at
    BEFORE UPDATE ON mailing_list
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mailing_recipient_updated_at'
    ) THEN
CREATE TRIGGER trg_mailing_recipient_updated_at
    BEFORE UPDATE ON mailing_recipient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
END IF;
END$$;

COMMIT;
